### PR TITLE
change user marker to differ from poi marker.

### LINKED ISSUE #158: change POI icon colour to not blue
- to differentiate GPS location marker from POI

### PR DESCRIPTION
**Pull request by jkkim98**
closes #158

vote with an approval review~!

### CODE REVIEW

**Review by JMu55 — APPROVED** [review]
Red GPS looks good :) .

**Comment by Elenaires** [comment]
this is good!

**Comment by JKKim98** [comment]
great work @BologneseBandit ~ !

**Review by LightXEthan — APPROVED** [review]
it's good! :)

**Pull request merged**
